// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package external_accounts

import (
	"fmt"
	"strings"
)

const (
	// BankAccountStatusPENDING is a BankAccountStatus of type PENDING.
	BankAccountStatusPENDING BankAccountStatus = "PENDING"
	// BankAccountStatusAPPROVED is a BankAccountStatus of type APPROVED.
	BankAccountStatusAPPROVED BankAccountStatus = "APPROVED"
	// BankAccountStatusFAILED is a BankAccountStatus of type FAILED.
	BankAccountStatusFAILED BankAccountStatus = "FAILED"
)

var ErrInvalidBankAccountStatus = fmt.Errorf("not a valid BankAccountStatus, try [%s]", strings.Join(_BankAccountStatusNames, ", "))

var _BankAccountStatusNames = []string{
	string(BankAccountStatusPENDING),
	string(BankAccountStatusAPPROVED),
	string(BankAccountStatusFAILED),
}

// BankAccountStatusNames returns a list of possible string values of BankAccountStatus.
func BankAccountStatusNames() []string {
	tmp := make([]string, len(_BankAccountStatusNames))
	copy(tmp, _BankAccountStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x BankAccountStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BankAccountStatus) IsValid() bool {
	_, err := ParseBankAccountStatus(string(x))
	return err == nil
}

var _BankAccountStatusValue = map[string]BankAccountStatus{
	"PENDING":  BankAccountStatusPENDING,
	"pending":  BankAccountStatusPENDING,
	"APPROVED": BankAccountStatusAPPROVED,
	"approved": BankAccountStatusAPPROVED,
	"FAILED":   BankAccountStatusFAILED,
	"failed":   BankAccountStatusFAILED,
}

// ParseBankAccountStatus attempts to convert a string to a BankAccountStatus.
func ParseBankAccountStatus(name string) (BankAccountStatus, error) {
	if x, ok := _BankAccountStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _BankAccountStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return BankAccountStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidBankAccountStatus)
}

// MarshalText implements the text marshaller method.
func (x BankAccountStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BankAccountStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseBankAccountStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *BankAccountStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// BankNetworkNameUSACH is a BankNetworkName of type US_ACH.
	BankNetworkNameUSACH BankNetworkName = "US_ACH"
	// BankNetworkNameSWIFT is a BankNetworkName of type SWIFT.
	BankNetworkNameSWIFT BankNetworkName = "SWIFT"
	// BankNetworkNameUSFEDWIRE is a BankNetworkName of type US_FEDWIRE.
	BankNetworkNameUSFEDWIRE BankNetworkName = "US_FEDWIRE"
)

var ErrInvalidBankNetworkName = fmt.Errorf("not a valid BankNetworkName, try [%s]", strings.Join(_BankNetworkNameNames, ", "))

var _BankNetworkNameNames = []string{
	string(BankNetworkNameUSACH),
	string(BankNetworkNameSWIFT),
	string(BankNetworkNameUSFEDWIRE),
}

// BankNetworkNameNames returns a list of possible string values of BankNetworkName.
func BankNetworkNameNames() []string {
	tmp := make([]string, len(_BankNetworkNameNames))
	copy(tmp, _BankNetworkNameNames)
	return tmp
}

// String implements the Stringer interface.
func (x BankNetworkName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BankNetworkName) IsValid() bool {
	_, err := ParseBankNetworkName(string(x))
	return err == nil
}

var _BankNetworkNameValue = map[string]BankNetworkName{
	"US_ACH":     BankNetworkNameUSACH,
	"us_ach":     BankNetworkNameUSACH,
	"SWIFT":      BankNetworkNameSWIFT,
	"swift":      BankNetworkNameSWIFT,
	"US_FEDWIRE": BankNetworkNameUSFEDWIRE,
	"us_fedwire": BankNetworkNameUSFEDWIRE,
}

// ParseBankNetworkName attempts to convert a string to a BankNetworkName.
func ParseBankNetworkName(name string) (BankNetworkName, error) {
	if x, ok := _BankNetworkNameValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _BankNetworkNameValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return BankNetworkName(""), fmt.Errorf("%s is %w", name, ErrInvalidBankNetworkName)
}

// MarshalText implements the text marshaller method.
func (x BankNetworkName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BankNetworkName) UnmarshalText(text []byte) error {
	tmp, err := ParseBankNetworkName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *BankNetworkName) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// CurrencyUSD is a Currency of type USD.
	CurrencyUSD Currency = "USD"
)

var ErrInvalidCurrency = fmt.Errorf("not a valid Currency, try [%s]", strings.Join(_CurrencyNames, ", "))

var _CurrencyNames = []string{
	string(CurrencyUSD),
}

// CurrencyNames returns a list of possible string values of Currency.
func CurrencyNames() []string {
	tmp := make([]string, len(_CurrencyNames))
	copy(tmp, _CurrencyNames)
	return tmp
}

// String implements the Stringer interface.
func (x Currency) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Currency) IsValid() bool {
	_, err := ParseCurrency(string(x))
	return err == nil
}

var _CurrencyValue = map[string]Currency{
	"USD": CurrencyUSD,
	"usd": CurrencyUSD,
}

// ParseCurrency attempts to convert a string to a Currency.
func ParseCurrency(name string) (Currency, error) {
	if x, ok := _CurrencyValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _CurrencyValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Currency(""), fmt.Errorf("%s is %w", name, ErrInvalidCurrency)
}

// MarshalText implements the text marshaller method.
func (x Currency) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Currency) UnmarshalText(text []byte) error {
	tmp, err := ParseCurrency(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Currency) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
