// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package auto_conversion_rules

import (
	"fmt"
	"strings"
)

const (
	// DepositInfoStatusPENDING is a DepositInfoStatus of type PENDING.
	DepositInfoStatusPENDING DepositInfoStatus = "PENDING"
	// DepositInfoStatusACTIVE is a DepositInfoStatus of type ACTIVE.
	DepositInfoStatusACTIVE DepositInfoStatus = "ACTIVE"
	// DepositInfoStatusINACTIVE is a DepositInfoStatus of type INACTIVE.
	DepositInfoStatusINACTIVE DepositInfoStatus = "INACTIVE"
)

var ErrInvalidDepositInfoStatus = fmt.Errorf("not a valid DepositInfoStatus, try [%s]", strings.Join(_DepositInfoStatusNames, ", "))

var _DepositInfoStatusNames = []string{
	string(DepositInfoStatusPENDING),
	string(DepositInfoStatusACTIVE),
	string(DepositInfoStatusINACTIVE),
}

// DepositInfoStatusNames returns a list of possible string values of DepositInfoStatus.
func DepositInfoStatusNames() []string {
	tmp := make([]string, len(_DepositInfoStatusNames))
	copy(tmp, _DepositInfoStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x DepositInfoStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DepositInfoStatus) IsValid() bool {
	_, err := ParseDepositInfoStatus(string(x))
	return err == nil
}

var _DepositInfoStatusValue = map[string]DepositInfoStatus{
	"PENDING":  DepositInfoStatusPENDING,
	"pending":  DepositInfoStatusPENDING,
	"ACTIVE":   DepositInfoStatusACTIVE,
	"active":   DepositInfoStatusACTIVE,
	"INACTIVE": DepositInfoStatusINACTIVE,
	"inactive": DepositInfoStatusINACTIVE,
}

// ParseDepositInfoStatus attempts to convert a string to a DepositInfoStatus.
func ParseDepositInfoStatus(name string) (DepositInfoStatus, error) {
	if x, ok := _DepositInfoStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _DepositInfoStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return DepositInfoStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDepositInfoStatus)
}

// MarshalText implements the text marshaller method.
func (x DepositInfoStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DepositInfoStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseDepositInfoStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *DepositInfoStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// RuleStatusPENDING is a RuleStatus of type PENDING.
	RuleStatusPENDING RuleStatus = "PENDING"
	// RuleStatusACTIVE is a RuleStatus of type ACTIVE.
	RuleStatusACTIVE RuleStatus = "ACTIVE"
	// RuleStatusINACTIVE is a RuleStatus of type INACTIVE.
	RuleStatusINACTIVE RuleStatus = "INACTIVE"
)

var ErrInvalidRuleStatus = fmt.Errorf("not a valid RuleStatus, try [%s]", strings.Join(_RuleStatusNames, ", "))

var _RuleStatusNames = []string{
	string(RuleStatusPENDING),
	string(RuleStatusACTIVE),
	string(RuleStatusINACTIVE),
}

// RuleStatusNames returns a list of possible string values of RuleStatus.
func RuleStatusNames() []string {
	tmp := make([]string, len(_RuleStatusNames))
	copy(tmp, _RuleStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x RuleStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RuleStatus) IsValid() bool {
	_, err := ParseRuleStatus(string(x))
	return err == nil
}

var _RuleStatusValue = map[string]RuleStatus{
	"PENDING":  RuleStatusPENDING,
	"pending":  RuleStatusPENDING,
	"ACTIVE":   RuleStatusACTIVE,
	"active":   RuleStatusACTIVE,
	"INACTIVE": RuleStatusINACTIVE,
	"inactive": RuleStatusINACTIVE,
}

// ParseRuleStatus attempts to convert a string to a RuleStatus.
func ParseRuleStatus(name string) (RuleStatus, error) {
	if x, ok := _RuleStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _RuleStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return RuleStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidRuleStatus)
}

// MarshalText implements the text marshaller method.
func (x RuleStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RuleStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseRuleStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RuleStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
