// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package simulations

import (
	"fmt"
	"strings"
)

const (
	// WalletNetworkNameARBITRUM is a WalletNetworkName of type ARBITRUM.
	WalletNetworkNameARBITRUM WalletNetworkName = "ARBITRUM"
	// WalletNetworkNameAVALANCHE is a WalletNetworkName of type AVALANCHE.
	WalletNetworkNameAVALANCHE WalletNetworkName = "AVALANCHE"
	// WalletNetworkNameBASE is a WalletNetworkName of type BASE.
	WalletNetworkNameBASE WalletNetworkName = "BASE"
	// WalletNetworkNameBNBCHAIN is a WalletNetworkName of type BNBCHAIN.
	WalletNetworkNameBNBCHAIN WalletNetworkName = "BNBCHAIN"
	// WalletNetworkNameETHEREUM is a WalletNetworkName of type ETHEREUM.
	WalletNetworkNameETHEREUM WalletNetworkName = "ETHEREUM"
	// WalletNetworkNamePOLYGON is a WalletNetworkName of type POLYGON.
	WalletNetworkNamePOLYGON WalletNetworkName = "POLYGON"
	// WalletNetworkNameSOLANA is a WalletNetworkName of type SOLANA.
	WalletNetworkNameSOLANA WalletNetworkName = "SOLANA"
)

var ErrInvalidWalletNetworkName = fmt.Errorf("not a valid WalletNetworkName, try [%s]", strings.Join(_WalletNetworkNameNames, ", "))

var _WalletNetworkNameNames = []string{
	string(WalletNetworkNameARBITRUM),
	string(WalletNetworkNameAVALANCHE),
	string(WalletNetworkNameBASE),
	string(WalletNetworkNameBNBCHAIN),
	string(WalletNetworkNameETHEREUM),
	string(WalletNetworkNamePOLYGON),
	string(WalletNetworkNameSOLANA),
}

// WalletNetworkNameNames returns a list of possible string values of WalletNetworkName.
func WalletNetworkNameNames() []string {
	tmp := make([]string, len(_WalletNetworkNameNames))
	copy(tmp, _WalletNetworkNameNames)
	return tmp
}

// String implements the Stringer interface.
func (x WalletNetworkName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WalletNetworkName) IsValid() bool {
	_, err := ParseWalletNetworkName(string(x))
	return err == nil
}

var _WalletNetworkNameValue = map[string]WalletNetworkName{
	"ARBITRUM":  WalletNetworkNameARBITRUM,
	"arbitrum":  WalletNetworkNameARBITRUM,
	"AVALANCHE": WalletNetworkNameAVALANCHE,
	"avalanche": WalletNetworkNameAVALANCHE,
	"BASE":      WalletNetworkNameBASE,
	"base":      WalletNetworkNameBASE,
	"BNBCHAIN":  WalletNetworkNameBNBCHAIN,
	"bnbchain":  WalletNetworkNameBNBCHAIN,
	"ETHEREUM":  WalletNetworkNameETHEREUM,
	"ethereum":  WalletNetworkNameETHEREUM,
	"POLYGON":   WalletNetworkNamePOLYGON,
	"polygon":   WalletNetworkNamePOLYGON,
	"SOLANA":    WalletNetworkNameSOLANA,
	"solana":    WalletNetworkNameSOLANA,
}

// ParseWalletNetworkName attempts to convert a string to a WalletNetworkName.
func ParseWalletNetworkName(name string) (WalletNetworkName, error) {
	if x, ok := _WalletNetworkNameValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _WalletNetworkNameValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return WalletNetworkName(""), fmt.Errorf("%s is %w", name, ErrInvalidWalletNetworkName)
}

// MarshalText implements the text marshaller method.
func (x WalletNetworkName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *WalletNetworkName) UnmarshalText(text []byte) error {
	tmp, err := ParseWalletNetworkName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *WalletNetworkName) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
