// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package recipient

import (
	"fmt"
	"strings"
)

const (
	// RecipientRelationshipEmployee is a RecipientRelationship of type employee.
	RecipientRelationshipEmployee RecipientRelationship = "employee"
	// RecipientRelationshipContractor is a RecipientRelationship of type contractor.
	RecipientRelationshipContractor RecipientRelationship = "contractor"
	// RecipientRelationshipVendor is a RecipientRelationship of type vendor.
	RecipientRelationshipVendor RecipientRelationship = "vendor"
	// RecipientRelationshipSubsidiary is a RecipientRelationship of type subsidiary.
	RecipientRelationshipSubsidiary RecipientRelationship = "subsidiary"
	// RecipientRelationshipMerchant is a RecipientRelationship of type merchant.
	RecipientRelationshipMerchant RecipientRelationship = "merchant"
	// RecipientRelationshipCustomer is a RecipientRelationship of type customer.
	RecipientRelationshipCustomer RecipientRelationship = "customer"
	// RecipientRelationshipLandlord is a RecipientRelationship of type landlord.
	RecipientRelationshipLandlord RecipientRelationship = "landlord"
	// RecipientRelationshipFamily is a RecipientRelationship of type family.
	RecipientRelationshipFamily RecipientRelationship = "family"
	// RecipientRelationshipOther is a RecipientRelationship of type other.
	RecipientRelationshipOther RecipientRelationship = "other"
)

var ErrInvalidRecipientRelationship = fmt.Errorf("not a valid RecipientRelationship, try [%s]", strings.Join(_RecipientRelationshipNames, ", "))

var _RecipientRelationshipNames = []string{
	string(RecipientRelationshipEmployee),
	string(RecipientRelationshipContractor),
	string(RecipientRelationshipVendor),
	string(RecipientRelationshipSubsidiary),
	string(RecipientRelationshipMerchant),
	string(RecipientRelationshipCustomer),
	string(RecipientRelationshipLandlord),
	string(RecipientRelationshipFamily),
	string(RecipientRelationshipOther),
}

// RecipientRelationshipNames returns a list of possible string values of RecipientRelationship.
func RecipientRelationshipNames() []string {
	tmp := make([]string, len(_RecipientRelationshipNames))
	copy(tmp, _RecipientRelationshipNames)
	return tmp
}

// String implements the Stringer interface.
func (x RecipientRelationship) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RecipientRelationship) IsValid() bool {
	_, err := ParseRecipientRelationship(string(x))
	return err == nil
}

var _RecipientRelationshipValue = map[string]RecipientRelationship{
	"employee":   RecipientRelationshipEmployee,
	"contractor": RecipientRelationshipContractor,
	"vendor":     RecipientRelationshipVendor,
	"subsidiary": RecipientRelationshipSubsidiary,
	"merchant":   RecipientRelationshipMerchant,
	"customer":   RecipientRelationshipCustomer,
	"landlord":   RecipientRelationshipLandlord,
	"family":     RecipientRelationshipFamily,
	"other":      RecipientRelationshipOther,
}

// ParseRecipientRelationship attempts to convert a string to a RecipientRelationship.
func ParseRecipientRelationship(name string) (RecipientRelationship, error) {
	if x, ok := _RecipientRelationshipValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _RecipientRelationshipValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return RecipientRelationship(""), fmt.Errorf("%s is %w", name, ErrInvalidRecipientRelationship)
}

// MarshalText implements the text marshaller method.
func (x RecipientRelationship) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RecipientRelationship) UnmarshalText(text []byte) error {
	tmp, err := ParseRecipientRelationship(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RecipientRelationship) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// RecipientStatusActive is a RecipientStatus of type active.
	RecipientStatusActive RecipientStatus = "active"
	// RecipientStatusInReview is a RecipientStatus of type in_review.
	RecipientStatusInReview RecipientStatus = "in_review"
	// RecipientStatusFailed is a RecipientStatus of type failed.
	RecipientStatusFailed RecipientStatus = "failed"
)

var ErrInvalidRecipientStatus = fmt.Errorf("not a valid RecipientStatus, try [%s]", strings.Join(_RecipientStatusNames, ", "))

var _RecipientStatusNames = []string{
	string(RecipientStatusActive),
	string(RecipientStatusInReview),
	string(RecipientStatusFailed),
}

// RecipientStatusNames returns a list of possible string values of RecipientStatus.
func RecipientStatusNames() []string {
	tmp := make([]string, len(_RecipientStatusNames))
	copy(tmp, _RecipientStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x RecipientStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RecipientStatus) IsValid() bool {
	_, err := ParseRecipientStatus(string(x))
	return err == nil
}

var _RecipientStatusValue = map[string]RecipientStatus{
	"active":    RecipientStatusActive,
	"in_review": RecipientStatusInReview,
	"failed":    RecipientStatusFailed,
}

// ParseRecipientStatus attempts to convert a string to a RecipientStatus.
func ParseRecipientStatus(name string) (RecipientStatus, error) {
	if x, ok := _RecipientStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _RecipientStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return RecipientStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidRecipientStatus)
}

// MarshalText implements the text marshaller method.
func (x RecipientStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RecipientStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseRecipientStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RecipientStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// RecipientTypeIndividual is a RecipientType of type individual.
	RecipientTypeIndividual RecipientType = "individual"
	// RecipientTypeCompany is a RecipientType of type company.
	RecipientTypeCompany RecipientType = "company"
)

var ErrInvalidRecipientType = fmt.Errorf("not a valid RecipientType, try [%s]", strings.Join(_RecipientTypeNames, ", "))

var _RecipientTypeNames = []string{
	string(RecipientTypeIndividual),
	string(RecipientTypeCompany),
}

// RecipientTypeNames returns a list of possible string values of RecipientType.
func RecipientTypeNames() []string {
	tmp := make([]string, len(_RecipientTypeNames))
	copy(tmp, _RecipientTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x RecipientType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RecipientType) IsValid() bool {
	_, err := ParseRecipientType(string(x))
	return err == nil
}

var _RecipientTypeValue = map[string]RecipientType{
	"individual": RecipientTypeIndividual,
	"company":    RecipientTypeCompany,
}

// ParseRecipientType attempts to convert a string to a RecipientType.
func ParseRecipientType(name string) (RecipientType, error) {
	if x, ok := _RecipientTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _RecipientTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return RecipientType(""), fmt.Errorf("%s is %w", name, ErrInvalidRecipientType)
}

// MarshalText implements the text marshaller method.
func (x RecipientType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RecipientType) UnmarshalText(text []byte) error {
	tmp, err := ParseRecipientType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RecipientType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
